title: yabaitech.tokyo
email: admin@yabaitech.tokyo
description: >-
  yabaitech.tokyoはコンピュータサイエンスに関する話題を広くゆるく扱うサークルです。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yabaitech.tokyo"
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
